// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api_logger.proto

// SPDX-FileCopyrightText: 2025 EasyTier Contributors
// SPDX-License-Identifier: LGPL-3.0-only

package api_logger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_DISABLED LogLevel = 0
	LogLevel_ERROR    LogLevel = 1
	LogLevel_WARNING  LogLevel = 2
	LogLevel_INFO     LogLevel = 3
	LogLevel_DEBUG    LogLevel = 4
	LogLevel_TRACE    LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "DISABLED",
		1: "ERROR",
		2: "WARNING",
		3: "INFO",
		4: "DEBUG",
		5: "TRACE",
	}
	LogLevel_value = map[string]int32{
		"DISABLED": 0,
		"ERROR":    1,
		"WARNING":  2,
		"INFO":     3,
		"DEBUG":    4,
		"TRACE":    5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_logger_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_api_logger_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_logger_proto_rawDescGZIP(), []int{0}
}

type SetLoggerConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=api.logger.LogLevel" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoggerConfigRequest) Reset() {
	*x = SetLoggerConfigRequest{}
	mi := &file_api_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoggerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoggerConfigRequest) ProtoMessage() {}

func (x *SetLoggerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoggerConfigRequest.ProtoReflect.Descriptor instead.
func (*SetLoggerConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_logger_proto_rawDescGZIP(), []int{0}
}

func (x *SetLoggerConfigRequest) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_DISABLED
}

type SetLoggerConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoggerConfigResponse) Reset() {
	*x = SetLoggerConfigResponse{}
	mi := &file_api_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoggerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoggerConfigResponse) ProtoMessage() {}

func (x *SetLoggerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoggerConfigResponse.ProtoReflect.Descriptor instead.
func (*SetLoggerConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_logger_proto_rawDescGZIP(), []int{1}
}

type GetLoggerConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoggerConfigRequest) Reset() {
	*x = GetLoggerConfigRequest{}
	mi := &file_api_logger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoggerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoggerConfigRequest) ProtoMessage() {}

func (x *GetLoggerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_logger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoggerConfigRequest.ProtoReflect.Descriptor instead.
func (*GetLoggerConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_logger_proto_rawDescGZIP(), []int{2}
}

type GetLoggerConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=api.logger.LogLevel" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoggerConfigResponse) Reset() {
	*x = GetLoggerConfigResponse{}
	mi := &file_api_logger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoggerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoggerConfigResponse) ProtoMessage() {}

func (x *GetLoggerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_logger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoggerConfigResponse.ProtoReflect.Descriptor instead.
func (*GetLoggerConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_logger_proto_rawDescGZIP(), []int{3}
}

func (x *GetLoggerConfigResponse) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_DISABLED
}

var File_api_logger_proto protoreflect.FileDescriptor

const file_api_logger_proto_rawDesc = "" +
	"\n" +
	"\x10api_logger.proto\x12\n" +
	"api.logger\"D\n" +
	"\x16SetLoggerConfigRequest\x12*\n" +
	"\x05level\x18\x01 \x01(\x0e2\x14.api.logger.LogLevelR\x05level\"\x19\n" +
	"\x17SetLoggerConfigResponse\"\x18\n" +
	"\x16GetLoggerConfigRequest\"E\n" +
	"\x17GetLoggerConfigResponse\x12*\n" +
	"\x05level\x18\x01 \x01(\x0e2\x14.api.logger.LogLevelR\x05level*P\n" +
	"\bLogLevel\x12\f\n" +
	"\bDISABLED\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\b\n" +
	"\x04INFO\x10\x03\x12\t\n" +
	"\x05DEBUG\x10\x04\x12\t\n" +
	"\x05TRACE\x10\x052\xc3\x01\n" +
	"\tLoggerRpc\x12Z\n" +
	"\x0fSetLoggerConfig\x12\".api.logger.SetLoggerConfigRequest\x1a#.api.logger.SetLoggerConfigResponse\x12Z\n" +
	"\x0fGetLoggerConfig\x12\".api.logger.GetLoggerConfigRequest\x1a#.api.logger.GetLoggerConfigResponseb\x06proto3"

var (
	file_api_logger_proto_rawDescOnce sync.Once
	file_api_logger_proto_rawDescData []byte
)

func file_api_logger_proto_rawDescGZIP() []byte {
	file_api_logger_proto_rawDescOnce.Do(func() {
		file_api_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_logger_proto_rawDesc), len(file_api_logger_proto_rawDesc)))
	})
	return file_api_logger_proto_rawDescData
}

var file_api_logger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_logger_proto_goTypes = []any{
	(LogLevel)(0),                   // 0: api.logger.LogLevel
	(*SetLoggerConfigRequest)(nil),  // 1: api.logger.SetLoggerConfigRequest
	(*SetLoggerConfigResponse)(nil), // 2: api.logger.SetLoggerConfigResponse
	(*GetLoggerConfigRequest)(nil),  // 3: api.logger.GetLoggerConfigRequest
	(*GetLoggerConfigResponse)(nil), // 4: api.logger.GetLoggerConfigResponse
}
var file_api_logger_proto_depIdxs = []int32{
	0, // 0: api.logger.SetLoggerConfigRequest.level:type_name -> api.logger.LogLevel
	0, // 1: api.logger.GetLoggerConfigResponse.level:type_name -> api.logger.LogLevel
	1, // 2: api.logger.LoggerRpc.SetLoggerConfig:input_type -> api.logger.SetLoggerConfigRequest
	3, // 3: api.logger.LoggerRpc.GetLoggerConfig:input_type -> api.logger.GetLoggerConfigRequest
	2, // 4: api.logger.LoggerRpc.SetLoggerConfig:output_type -> api.logger.SetLoggerConfigResponse
	4, // 5: api.logger.LoggerRpc.GetLoggerConfig:output_type -> api.logger.GetLoggerConfigResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_logger_proto_init() }
func file_api_logger_proto_init() {
	if File_api_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_logger_proto_rawDesc), len(file_api_logger_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_logger_proto_goTypes,
		DependencyIndexes: file_api_logger_proto_depIdxs,
		EnumInfos:         file_api_logger_proto_enumTypes,
		MessageInfos:      file_api_logger_proto_msgTypes,
	}.Build()
	File_api_logger_proto = out.File
	file_api_logger_proto_goTypes = nil
	file_api_logger_proto_depIdxs = nil
}
