// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: magic_dns.proto

// SPDX-FileCopyrightText: 2025 EasyTier Contributors
// SPDX-License-Identifier: LGPL-3.0-only

package magic_dns

import (
	api_instance "github.com/EasyTier/EasyTier/go/internal/proto/api_instance"
	common "github.com/EasyTier/EasyTier/go/internal/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DnsRecordA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *common.Ipv4Addr       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int32                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsRecordA) Reset() {
	*x = DnsRecordA{}
	mi := &file_magic_dns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsRecordA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsRecordA) ProtoMessage() {}

func (x *DnsRecordA) ProtoReflect() protoreflect.Message {
	mi := &file_magic_dns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsRecordA.ProtoReflect.Descriptor instead.
func (*DnsRecordA) Descriptor() ([]byte, []int) {
	return file_magic_dns_proto_rawDescGZIP(), []int{0}
}

func (x *DnsRecordA) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DnsRecordA) GetValue() *common.Ipv4Addr {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DnsRecordA) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type DnsRecordSOA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsRecordSOA) Reset() {
	*x = DnsRecordSOA{}
	mi := &file_magic_dns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsRecordSOA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsRecordSOA) ProtoMessage() {}

func (x *DnsRecordSOA) ProtoReflect() protoreflect.Message {
	mi := &file_magic_dns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsRecordSOA.ProtoReflect.Descriptor instead.
func (*DnsRecordSOA) Descriptor() ([]byte, []int) {
	return file_magic_dns_proto_rawDescGZIP(), []int{1}
}

func (x *DnsRecordSOA) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DnsRecordSOA) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DnsRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Record:
	//
	//	*DnsRecord_A
	//	*DnsRecord_Soa
	Record        isDnsRecord_Record `protobuf_oneof:"record"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsRecord) Reset() {
	*x = DnsRecord{}
	mi := &file_magic_dns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsRecord) ProtoMessage() {}

func (x *DnsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_magic_dns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsRecord.ProtoReflect.Descriptor instead.
func (*DnsRecord) Descriptor() ([]byte, []int) {
	return file_magic_dns_proto_rawDescGZIP(), []int{2}
}

func (x *DnsRecord) GetRecord() isDnsRecord_Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *DnsRecord) GetA() *DnsRecordA {
	if x != nil {
		if x, ok := x.Record.(*DnsRecord_A); ok {
			return x.A
		}
	}
	return nil
}

func (x *DnsRecord) GetSoa() *DnsRecordSOA {
	if x != nil {
		if x, ok := x.Record.(*DnsRecord_Soa); ok {
			return x.Soa
		}
	}
	return nil
}

type isDnsRecord_Record interface {
	isDnsRecord_Record()
}

type DnsRecord_A struct {
	A *DnsRecordA `protobuf:"bytes,1,opt,name=a,proto3,oneof"`
}

type DnsRecord_Soa struct {
	Soa *DnsRecordSOA `protobuf:"bytes,2,opt,name=soa,proto3,oneof"`
}

func (*DnsRecord_A) isDnsRecord_Record() {}

func (*DnsRecord_Soa) isDnsRecord_Record() {}

type DnsRecordList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*DnsRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsRecordList) Reset() {
	*x = DnsRecordList{}
	mi := &file_magic_dns_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsRecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsRecordList) ProtoMessage() {}

func (x *DnsRecordList) ProtoReflect() protoreflect.Message {
	mi := &file_magic_dns_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsRecordList.ProtoReflect.Descriptor instead.
func (*DnsRecordList) Descriptor() ([]byte, []int) {
	return file_magic_dns_proto_rawDescGZIP(), []int{3}
}

func (x *DnsRecordList) GetRecords() []*DnsRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type UpdateDnsRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Routes        []*api_instance.Route  `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDnsRecordRequest) Reset() {
	*x = UpdateDnsRecordRequest{}
	mi := &file_magic_dns_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDnsRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDnsRecordRequest) ProtoMessage() {}

func (x *UpdateDnsRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magic_dns_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDnsRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateDnsRecordRequest) Descriptor() ([]byte, []int) {
	return file_magic_dns_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDnsRecordRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *UpdateDnsRecordRequest) GetRoutes() []*api_instance.Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type GetDnsRecordResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Records       map[string]*DnsRecordList `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDnsRecordResponse) Reset() {
	*x = GetDnsRecordResponse{}
	mi := &file_magic_dns_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDnsRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDnsRecordResponse) ProtoMessage() {}

func (x *GetDnsRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magic_dns_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDnsRecordResponse.ProtoReflect.Descriptor instead.
func (*GetDnsRecordResponse) Descriptor() ([]byte, []int) {
	return file_magic_dns_proto_rawDescGZIP(), []int{5}
}

func (x *GetDnsRecordResponse) GetRecords() map[string]*DnsRecordList {
	if x != nil {
		return x.Records
	}
	return nil
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_magic_dns_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magic_dns_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_magic_dns_proto_rawDescGZIP(), []int{6}
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_magic_dns_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magic_dns_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_magic_dns_proto_rawDescGZIP(), []int{7}
}

var File_magic_dns_proto protoreflect.FileDescriptor

const file_magic_dns_proto_rawDesc = "" +
	"\n" +
	"\x0fmagic_dns.proto\x12\tmagic_dns\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\x1a\x12api_instance.proto\"Z\n" +
	"\n" +
	"DnsRecordA\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.common.Ipv4AddrR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x05R\x03ttl\"8\n" +
	"\fDnsRecordSOA\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"i\n" +
	"\tDnsRecord\x12%\n" +
	"\x01a\x18\x01 \x01(\v2\x15.magic_dns.DnsRecordAH\x00R\x01a\x12+\n" +
	"\x03soa\x18\x02 \x01(\v2\x17.magic_dns.DnsRecordSOAH\x00R\x03soaB\b\n" +
	"\x06record\"?\n" +
	"\rDnsRecordList\x12.\n" +
	"\arecords\x18\x01 \x03(\v2\x14.magic_dns.DnsRecordR\arecords\"Y\n" +
	"\x16UpdateDnsRecordRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12+\n" +
	"\x06routes\x18\x02 \x03(\v2\x13.api.instance.RouteR\x06routes\"\xb4\x01\n" +
	"\x14GetDnsRecordResponse\x12F\n" +
	"\arecords\x18\x01 \x03(\v2,.magic_dns.GetDnsRecordResponse.RecordsEntryR\arecords\x1aT\n" +
	"\fRecordsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.magic_dns.DnsRecordListR\x05value:\x028\x01\"\x12\n" +
	"\x10HandshakeRequest\"\x13\n" +
	"\x11HandshakeResponse2\x8f\x02\n" +
	"\x11MagicDnsServerRpc\x12H\n" +
	"\tHandshake\x12\x1b.magic_dns.HandshakeRequest\x1a\x1c.magic_dns.HandshakeResponse\"\x00\x12)\n" +
	"\tHeartbeat\x12\f.common.Void\x1a\f.common.Void\"\x00\x12D\n" +
	"\x0fUpdateDnsRecord\x12!.magic_dns.UpdateDnsRecordRequest\x1a\f.common.Void\"\x00\x12?\n" +
	"\fGetDnsRecord\x12\f.common.Void\x1a\x1f.magic_dns.GetDnsRecordResponse\"\x00b\x06proto3"

var (
	file_magic_dns_proto_rawDescOnce sync.Once
	file_magic_dns_proto_rawDescData []byte
)

func file_magic_dns_proto_rawDescGZIP() []byte {
	file_magic_dns_proto_rawDescOnce.Do(func() {
		file_magic_dns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_magic_dns_proto_rawDesc), len(file_magic_dns_proto_rawDesc)))
	})
	return file_magic_dns_proto_rawDescData
}

var file_magic_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_magic_dns_proto_goTypes = []any{
	(*DnsRecordA)(nil),             // 0: magic_dns.DnsRecordA
	(*DnsRecordSOA)(nil),           // 1: magic_dns.DnsRecordSOA
	(*DnsRecord)(nil),              // 2: magic_dns.DnsRecord
	(*DnsRecordList)(nil),          // 3: magic_dns.DnsRecordList
	(*UpdateDnsRecordRequest)(nil), // 4: magic_dns.UpdateDnsRecordRequest
	(*GetDnsRecordResponse)(nil),   // 5: magic_dns.GetDnsRecordResponse
	(*HandshakeRequest)(nil),       // 6: magic_dns.HandshakeRequest
	(*HandshakeResponse)(nil),      // 7: magic_dns.HandshakeResponse
	nil,                            // 8: magic_dns.GetDnsRecordResponse.RecordsEntry
	(*common.Ipv4Addr)(nil),        // 9: common.Ipv4Addr
	(*api_instance.Route)(nil),     // 10: api.instance.Route
	(*common.Void)(nil),            // 11: common.Void
}
var file_magic_dns_proto_depIdxs = []int32{
	9,  // 0: magic_dns.DnsRecordA.value:type_name -> common.Ipv4Addr
	0,  // 1: magic_dns.DnsRecord.a:type_name -> magic_dns.DnsRecordA
	1,  // 2: magic_dns.DnsRecord.soa:type_name -> magic_dns.DnsRecordSOA
	2,  // 3: magic_dns.DnsRecordList.records:type_name -> magic_dns.DnsRecord
	10, // 4: magic_dns.UpdateDnsRecordRequest.routes:type_name -> api.instance.Route
	8,  // 5: magic_dns.GetDnsRecordResponse.records:type_name -> magic_dns.GetDnsRecordResponse.RecordsEntry
	3,  // 6: magic_dns.GetDnsRecordResponse.RecordsEntry.value:type_name -> magic_dns.DnsRecordList
	6,  // 7: magic_dns.MagicDnsServerRpc.Handshake:input_type -> magic_dns.HandshakeRequest
	11, // 8: magic_dns.MagicDnsServerRpc.Heartbeat:input_type -> common.Void
	4,  // 9: magic_dns.MagicDnsServerRpc.UpdateDnsRecord:input_type -> magic_dns.UpdateDnsRecordRequest
	11, // 10: magic_dns.MagicDnsServerRpc.GetDnsRecord:input_type -> common.Void
	7,  // 11: magic_dns.MagicDnsServerRpc.Handshake:output_type -> magic_dns.HandshakeResponse
	11, // 12: magic_dns.MagicDnsServerRpc.Heartbeat:output_type -> common.Void
	11, // 13: magic_dns.MagicDnsServerRpc.UpdateDnsRecord:output_type -> common.Void
	5,  // 14: magic_dns.MagicDnsServerRpc.GetDnsRecord:output_type -> magic_dns.GetDnsRecordResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_magic_dns_proto_init() }
func file_magic_dns_proto_init() {
	if File_magic_dns_proto != nil {
		return
	}
	file_magic_dns_proto_msgTypes[2].OneofWrappers = []any{
		(*DnsRecord_A)(nil),
		(*DnsRecord_Soa)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_magic_dns_proto_rawDesc), len(file_magic_dns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_magic_dns_proto_goTypes,
		DependencyIndexes: file_magic_dns_proto_depIdxs,
		MessageInfos:      file_magic_dns_proto_msgTypes,
	}.Build()
	File_magic_dns_proto = out.File
	file_magic_dns_proto_goTypes = nil
	file_magic_dns_proto_depIdxs = nil
}
